map_to_negativize(1,2,3,-9)
map_to_no_change(dune)
map_to_double(1,2,3,-9)
map_to_square(1,2,3,-9)
reduce_to_total(source_array)
reduce_to_total(source_array, starting_point)
reduce_to_all_true(source_array)
reduce_to_all_true(source_array)
reduce_to_any_true(source_array)
reduce_to_any_true(source_array)
